#!/bin/bash
#
# Thibault ANIN script's, to speed up the push of the exercises during the
# EPITA swimming pool (hence the name "epload" ^^)
#
#########################################################################

GIT_ENV='Path_To_Your_Repository' #<= change this

#########################################################################


SUCCESS="\033[37;1m[\033[32;1m+\033[37;1m]\033[0m "
INFO="\033[37;1m[\033[36;1m*\033[37;1m]\033[0m "
ERROR="\033[37;1m[\033[31;1m-\033[37;1m]\033[0m "

L_BRACKET="\033[37;1m[\033[0m"
R_BRACKET="\033[37;1m]\033[0m"

tag_name=$1
commit_msg=$2

function push_exercise () {
    commit_msg=$1
    tag_name=$2
    tag_msg=$3

    git add * &&
    echo -e $SUCCESS"\033[37;1mgit add *\033[00m" &&
    sleep 0.2 &&
    git commit -m "$commit_msg" &&
    echo -e $SUCCESS"\033[37;1mgit commit -m \"$commit_msg\"\033[00m" &&
    sleep 0.2 &&
    git tag -a $tag_name -m $tag_msg &&
    echo -e $SUCCESS"\033[37;1mgit tag -a \"$tag_name\" -m \"$tag_msg\"\033[00m" &&
    sleep 0.2 &&
    git push origin master --follow-tags &&
    echo -e $SUCCESS"\033[37;1mgit push origin master --follow-tags\033[00m" &&
    sleep 0.2
    #echo -e "git log" &&
    #git log
}

clear

if [[ $# -eq 0 ]]; then
    echo -e $ERROR"\033[37;1mHelp : ./epload.sh [tag_name] optional([commit_message])\033[00m\n"
    exit 1
fi

cd $GIT_ENV &&

if [[ $(echo -n $tag_name | tail -c 1) = '*' ]]; then
    echo -e "\n"$INFO"\033[32;3;1mAUTO MODE\033[00m\n"
    sleep 0.2

    ex_version=1
    ex_name=$(echo -n $tag_name | rev | cut -c 3- | rev | cut -c 11-)

    while [[ $(git log --decorate=short | grep "exercises-"$ex_name"-v"$ex_version) ]]; do
        ((ex_version++))
    done
    
    if [[ -z "$commit_msg" ]]; then
        type="update"
        if [[ $ex_version -eq 1 ]]; then
            type="add"
        fi

        commit_msg=$ex_name": "$type" "$ex_name".c"
    fi

    push_exercise "$commit_msg" "exercises-"$ex_name"-v"$ex_version $ex_name
else
    echo -e "\n"$INFO"\033[31;3;1mMANUAL MODE\033[00m\n"
    sleep 0.2

    if [[ -z "$tag_name" ]]; then
        echo -e "Manual mode requires a commit message."
        exit 1
    fi
    if [[ $(git log --decorate=short|grep $tag_name) ]]; then
        echo -e $ERROR"\033[37;1mThis tag name already exist !\033[00m\n"
        exit 1
    else
        echo -e $SUCCESS"\033[37;1mValid name\033[00m"
        push_exercise "$commit_msg" $tag_name $(echo -n $tag_name | rev | cut -c 4- | rev | cut -c 11-)
    fi
fi

echo
sleep 0.3
